name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: chipsu/rancher-deploy-action@v4
        with:
          url: ${{ secrets.RANCHER_URL }}
          access_key: ${{ secrets.RANCHER_ACCESS_KEY }}
          secret_key: ${{ secrets.RANCHER_SECRET_KEY }}
          stack: test-stack-1234
        env:
          DROPBOX_IMAGE: nginx
          DROPBOX_PATH: /tmp
          DROPBOX_SETTINGS_PATH: /tmp
